<a href="https://colab.research.google.com/github/ADYASHAMUNI/ADYASHAMUNI/blob/main/SVM_Explained_Iris_and_ionosphere_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import svm

![S2](iris2.png)

In [2]:
df = pd.read_csv('iris.data')

In [3]:
#df = pd.read_csv('ionosphere.csv')

In [4]:
df.head

<bound method NDFrame.head of      5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]>

![S1](iris.png)

In [5]:
df.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [6]:
df.columns = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
df['class'].value_counts()

class
Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: count, dtype: int64

In [7]:
#ionosphere
#df.columns = ['attr1', 'attr2', 'attr3', 'attr4', 'attr5', 'attr6', 'attr7', 'attr8', 'attr8', 'attr9', 'attr10', 'attr11', 'attr12', 'attr13',
#             'attr14', 'attr15','attr16', 'attr17','attr18', 'attr19','attr20', 'attr21','attr22', 'attr23','attr24', 'attr25','attr26', 'attr27',
#             'attr28', 'attr29','attr30', 'attr31','attr32', 'attr34', 'label']

In [8]:
df

sepal-length  sepal-width  petal-length  petal-width           class
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

In [10]:
y = df['class']

In [11]:
#y = df['label']

In [12]:
X = df.drop(columns=['class'])

In [13]:
#X = df.drop(columns=['label'])

In [14]:
X

sepal-length  sepal-width  petal-length  petal-width
0             4.9          3.0           1.4          0.2
1             4.7          3.2           1.3          0.2
2             4.6          3.1           1.5          0.2
3             5.0          3.6           1.4          0.2
4             5.4          3.9           1.7          0.4
..            ...          ...           ...          ...
144           6.7          3.0           5.2          2.3
145           6.3          2.5           5.0          1.9
146           6.5          3.0           5.2          2.0
147           6.2          3.4           5.4          2.3
148           5.9          3.0           5.1          1.8

[149 rows x 4 columns]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=42)

In [16]:
# Different Kernel that can be used  ---- --- ---- 'linear', 'poly', 'rbf'
model_svm = svm.SVC(kernel='rbf')

In [17]:
model_svm.fit(X_train, y_train)

SVC()

In [18]:
y_predicted = model_svm.predict(X_test)

In [19]:
print(classification_report(y_test,y_predicted))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        29
Iris-versicolor       0.95      0.88      0.91        24
 Iris-virginica       0.88      0.95      0.91        22

       accuracy                           0.95        75
      macro avg       0.94      0.94      0.94        75
   weighted avg       0.95      0.95      0.95        75



In [20]:
print(confusion_matrix(y_test, y_predicted))

[[29  0  0]
 [ 0 21  3]
 [ 0  1 21]]
